gnome-terminal --tab --title="1-50" --command="python3 login-api.py"
gnome-terminal --tab --title="2-51" --command="python3 upload_quiz_api.py"
gnome-terminal --tab --title="3-52" --command="python3 student-login-api.py"
gnome-terminal --tab --title="4-53" --command="python3 show_quiz.py"
gnome-terminal --tab --title="5-54" --command="python3 faculty_dashboard.py"
gnome-terminal --tab --title="6-55" --command="python3 student_dashboard.py"
gnome-terminal --tab --title="7-56" --command="python3 edit_quiz.py"
gnome-terminal --tab --title="8-57" --command="python3 generate_report.py"
